import glob
import logging
import os
from datetime import datetime, timedelta
from pathlib import Path

logger = logging.getLogger(__name__)

REPORT_DIR = Path("/app/reports")


REPORT_TEMPLATE = """<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><style>
body {{ font-family: -apple-system, sans-serif; margin: 20px; color: #333; }}
h1 {{ color: {title_color}; }}
table {{ border-collapse: collapse; width: 100%; margin: 16px 0; }}
th, td {{ border: 1px solid #ddd; padding: 8px 12px; text-align: left; }}
th {{ background: #f5f5f5; }}
.ok {{ color: #22c55e; font-weight: bold; }}
.fail {{ color: #ef4444; font-weight: bold; }}
.footer {{ color: #999; font-size: 12px; margin-top: 24px; }}
</style></head>
<body>
<h1>RAGcheck Health Report</h1>
<p><strong>Checked at:</strong> {timestamp}</p>
<p><strong>Overall:</strong> <span class="{status_class}">{overall} ({passed}/{total})</span></p>
<table>
<tr><th>Check</th><th>Status</th><th>Detail</th></tr>
{rows}
</table>
<p class="footer">Generated automatically by RAGcheck</p>
</body>
</html>"""


def render_html(report: dict) -> str:
    rows = ""
    for item in report["checks"]:
        status = '<span class="ok">OK</span>' if item["ok"] else '<span class="fail">FAIL</span>'
        rows += f"<tr><td>{item['name']}</td><td>{status}</td><td>{item['detail']}</td></tr>\n"

    title_color = "#22c55e" if report["all_ok"] else "#ef4444"
    status_class = "ok" if report["all_ok"] else "fail"

    return REPORT_TEMPLATE.format(
        title_color=title_color,
        timestamp=report["timestamp"],
        overall=report["overall"],
        status_class=status_class,
        passed=report["passed"],
        total=report["total"],
        rows=rows,
    )


def render_markdown(report: dict) -> str:
    lines = [
        "# RAGcheck Report",
        "",
        f"- Time: {report['timestamp']}",
        f"- Overall: {report['overall']} ({report['passed']}/{report['total']})",
        "",
        "| Check | Status | Detail |",
        "| --- | --- | --- |",
    ]

    for item in report["checks"]:
        status = "OK" if item["ok"] else "FAIL"
        detail = str(item["detail"]).replace("\n", " ").replace("|", "\\|")
        lines.append(f"| {item['name']} | {status} | {detail} |")

    lines.extend(["", "_Generated by RAGcheck_"])
    return "\n".join(lines)


def render_text(report: dict) -> str:
    lines = [
        "RAGcheck Report",
        f"Time: {report['timestamp']}",
        f"Overall: {report['overall']} ({report['passed']}/{report['total']})",
        "",
        "Details:",
    ]

    for item in report["checks"]:
        status = "OK" if item["ok"] else "FAIL"
        lines.append(f"{item['name']}: {status}")
        lines.append(f"  {item['detail']}")

    return "\n".join(lines)


def save_report(report: dict, html: str) -> str:
    REPORT_DIR.mkdir(parents=True, exist_ok=True)
    filename = f"report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.html"
    path = REPORT_DIR / filename
    path.write_text(html, encoding="utf-8")
    logger.info("Saved report: %s", path)
    return str(path)


def cleanup_old_reports(retention_days: int):
    cutoff = datetime.now() - timedelta(days=retention_days)
    pattern = str(REPORT_DIR / "report_*.html")
    removed = 0

    for file_path in glob.glob(pattern):
        try:
            name = Path(file_path).stem
            date_str = name.replace("report_", "")[:8]
            file_date = datetime.strptime(date_str, "%Y%m%d")
            if file_date < cutoff:
                os.remove(file_path)
                removed += 1
        except (ValueError, OSError):
            pass

    if removed:
        logger.info("Removed %d expired report(s)", removed)
